// Mock-Daten für lokale Entwicklung (bis Supabase live ist)
import { Deal } from './supabase';

export const MOCK_LIDL_STORE = {
  id: 'store-lidl',
  name: 'Lidl',
  slug: 'lidl',
  logo_url: null,
  primary_color: '#0050AA',
  text_color: '#FFE000',
};

export const MOCK_DEALS: Deal[] = [
  {
    id: '1',
    store_id: 'store-lidl',
    title: 'Milbona Magerquark',
    brand: 'Milbona',
    subtitle: '500g',
    price: 0.79,
    original_price: 1.29,
    app_price: null,
    is_app_exclusive: false,
    unit: '500g',
    price_per_unit: 1.58,
    price_per_unit_label: '1,58 € / kg',
    discount_pct: 39,
    valid_from: '2026-08-18',
    valid_to: '2026-08-23',
    timing_tag: 'MO_SA',
    image_url: 'https://placehold.co/400x400/0050AA/FFE000?text=Quark',
    category: 'Milch & Käse',
    tags: ['High Protein', 'Clean Eating', 'Basics'],
    is_non_food: false,
    is_junk_food: false,
    is_alcohol: false,
    scraped_at: new Date().toISOString(),
    store: MOCK_LIDL_STORE,
  },
  {
    id: '2',
    store_id: 'store-lidl',
    title: 'Hähnchen Brustfilet',
    brand: null,
    subtitle: 'je 800g',
    price: 4.99,
    original_price: 7.99,
    app_price: null,
    is_app_exclusive: false,
    unit: '800g',
    price_per_unit: 6.24,
    price_per_unit_label: '6,24 € / kg',
    discount_pct: 38,
    valid_from: '2026-08-18',
    valid_to: '2026-08-23',
    timing_tag: 'MO_SA',
    image_url: 'https://placehold.co/400x400/0050AA/FFE000?text=H%C3%A4hnchen',
    category: 'Fleisch & Fisch',
    tags: ['High Protein', 'Mageres Fleisch'],
    is_non_food: false,
    is_junk_food: false,
    is_alcohol: false,
    scraped_at: new Date().toISOString(),
    store: MOCK_LIDL_STORE,
  },
  {
    id: '3',
    store_id: 'store-lidl',
    title: 'Skyr Natur',
    brand: 'Milbona',
    subtitle: '500g',
    price: 1.19,
    original_price: 1.69,
    app_price: null,
    is_app_exclusive: false,
    unit: '500g',
    price_per_unit: 2.38,
    price_per_unit_label: '2,38 € / kg',
    discount_pct: 30,
    valid_from: '2026-08-18',
    valid_to: '2026-08-23',
    timing_tag: 'MO_SA',
    image_url: 'https://placehold.co/400x400/0050AA/FFE000?text=Skyr',
    category: 'Milch & Käse',
    tags: ['High Protein', 'Low Carb'],
    is_non_food: false,
    is_junk_food: false,
    is_alcohol: false,
    scraped_at: new Date().toISOString(),
    store: MOCK_LIDL_STORE,
  },
  {
    id: '4',
    store_id: 'store-lidl',
    title: 'Erdbeeren',
    brand: null,
    subtitle: 'Schale 500g',
    price: 1.49,
    original_price: 2.49,
    app_price: null,
    is_app_exclusive: false,
    unit: '500g',
    price_per_unit: 2.98,
    price_per_unit_label: '2,98 € / kg',
    discount_pct: 40,
    valid_from: '2026-08-21',
    valid_to: '2026-08-21',
    timing_tag: 'SATURDAY_ONLY',
    image_url: 'https://placehold.co/400x400/0050AA/FFE000?text=Erdbeeren',
    category: 'Obst & Gemüse',
    tags: ['Obst & Gemüse', 'Basics'],
    is_non_food: false,
    is_junk_food: false,
    is_alcohol: false,
    scraped_at: new Date().toISOString(),
    store: MOCK_LIDL_STORE,
  },
  {
    id: '5',
    store_id: 'store-lidl',
    title: 'Kaffeevollautomat',
    brand: 'Silvercrest',
    subtitle: '1500W',
    price: 149.00,
    original_price: 249.00,
    app_price: null,
    is_app_exclusive: false,
    unit: null,
    price_per_unit: null,
    price_per_unit_label: null,
    discount_pct: 40,
    valid_from: '2026-08-18',
    valid_to: '2026-08-23',
    timing_tag: 'MO_SA',
    image_url: 'https://placehold.co/400x400/888/FFF?text=Kaffeemaschine',
    category: 'Non-Food',
    tags: [],
    is_non_food: true,
    is_junk_food: false,
    is_alcohol: false,
    scraped_at: new Date().toISOString(),
    store: MOCK_LIDL_STORE,
  },
  {
    id: '6',
    store_id: 'store-lidl',
    title: 'Lachs Filet',
    brand: null,
    subtitle: 'ASC-zertifiziert, tiefgefroren, 500g',
    price: 4.29,
    original_price: 6.99,
    app_price: null,
    is_app_exclusive: false,
    unit: '500g',
    price_per_unit: 8.58,
    price_per_unit_label: '8,58 € / kg',
    discount_pct: 39,
    valid_from: '2026-08-18',
    valid_to: '2026-08-23',
    timing_tag: 'MO_SA',
    image_url: 'https://placehold.co/400x400/0050AA/FFE000?text=Lachs',
    category: 'Fleisch & Fisch',
    tags: ['High Protein', 'Omega-3'],
    is_non_food: false,
    is_junk_food: false,
    is_alcohol: false,
    scraped_at: new Date().toISOString(),
    store: MOCK_LIDL_STORE,
  },
];
